language: go
go:
- '1.11'
deploy:
  provider: releases
  api_key: "$GITHUB_AUTH"
  file_glob: true
  file: build/envelope-*
  skip_cleanup: true
  on:
    tags: true
install:
- make dev-deps
script:
- make all
env:
  global:
  - AWS_REGION=us-east-1
  - CGO_ENABLED=0

  # GITHUB_AUTH
  - secure: GXCgRP8AoijSNd3Ub9CObnJ5/vfRFxSgLOfY6JwLxyOFkbkaLn3bm1K3sa/E9PN26Fn9dRWUYJQmndmX6Z0CwWwIByfKfzNYisAhrFH4mCCLYKPnOARt3ltoVz7ItwdfzBIwOkmfqFJP5rpMfzbqg/WtWclHctK4S9joFmH8vvijEWu6z87ZkaOVoW1j0XdcMjCoPPbb7WsAiQiP2p99/szNCjsS8/3C2kkuJyrdpnDwubwbqtgvg4lUkDoadtWHE0+wyWa5HF+oF3W2sb0jllFPuM5yqb9fHRb0F2Ni8kL9UGW7pYmvGJBm7IZHSxq2V2CloCNOe86OIcyy6tZAdflca2FN0c9fhfdUBdHLiMcLkH9wRt33GEReMAjAhRHWXl8Mnz95KR4IplyUNA+peU+zL9kNypPP1YMEpzSlob3P4aTVbb0M2zsKmZa9cII0WY3Mtso3wuWj3v+Hz0pDYzMaqN7luQEil1jg47vtB1vLszEnsNnlaxJmBQFE8fTqhsSRiOpA0moMtiD5XOQYc/JLwJg11G/rlCsYdDMr5zPDWxi+JNI89fEWvM6MAEczePu1Az+V0yoXzebyMSD7xyJ2zjtZSK2j3Avbx7yqwYhFDI/5fOKiEiz03AY0Y9kYbov+/ZMKzucJnyPf7vokao9pd75bfw8oow6Yxxk0tNg=

  # AWS_ACCESS_KEY_ID
  - secure: g4B/v/COp1lMAWHd0+dzxlbyjC74UwI1KbY4N8rNKtVTeu+u+VPN7tG0Av+clkCxjiEk2m+l9+s8DE3VOI3xibwNGYwsrzPtdX9gDdIVvoTjrTsOwvN5wdnwtUeOeHsAn0FTyCFYMkiAGUYEUd54pw8LC+sr0lXffFhMGxPPC30olo3eCuszarAnRGO9EPyNvwilrseyYviTkUEHo/NEJycK9UQxYGcNNl8zvywMeUwaJ79UQi1UFta+CaDWLrNgtMJcLIZwAh5FFjT7/a6HxP5BChnrdJlplmyk04ABb1To1G8QqK0Nf8xHD4irrVi16KSxNegZOOgCHK7krisDUsLchlr03iciYsgC4m3NdurXLnRlzUTcwlgW0S9MpK52hi4pIn2ZTAKGBkBWaBEagZSwrNZ7NqVrdTBfUQUCNSh042XboSTnrb7/VjSxHaE0sy9TuJoPtarQnMWqG32x15Fmcg6Xoa4iLUmCImHs4RGtEoDKVMoMEBPqf9/QLa0HDFkHBfvSF+LLSAFO4FWlrktTpp0imFZDAQIDwLzAtDHrHIjNTmUioAHKTcW29uZDbsSPnqf0vdMpIzLus1KKB+wNG0gxdHN/F41HVuBZ550gB1pbzx04XdqiDKK0Wq7Lhwaz0iLRVxWE/Ksqf+qWqItTUn7vFI/svdqYn9H9rnM=
  
  # AWS_SECRET_ACCESS_KEY
  - secure: iFmp3/5jPT0kUddN1poN14UH/VF1CrBFQ4vwwgySvqzWxQ9PpLkU1uVV5+j0fW/E35+7wBOWC/PVmHTSasLH1rZ9VruNLE4LqKGTa7tsSFg3Gd+e9rg9U/INn1RG+VIqEl1cWxqBhnxjJREI3uD95OBeW5yewkjKrqDFSvZLtuPJe+wturcPdrtlRpLnhtAX01a5RDFL9l2LmMl1tNNbpW38jnU5oUi5g+5o5vddoFtLi0FycxoOxoe/OqcLd9V4GVg560+jjHW9kvk99kJDGdEC1vqZpFanxuC3MhIDRk9370Cw7f5nAEc/sTQ7r3c2qpNvJ8UaUgKylzqaMnuF3wG3WoQNQ0idtP68BbYGBy8P/PkitZsM+ka3SXOKVAS5d96lETRQPIL1IiFu8J2w+y8ahdhTGisU2bWHNgkQdhm3MNe6Oy8T3r9GBBmPmUbyXD5sBBkNyWSqpG1d/ou6pUFHRhLtgTs2ax+AaEO9FAkLNnQzVHkFdQIMHDhTdq6KTLrYAx9KWER7IDftMtbNWF4KXZjsLU8olI4idt9VVKPZ5T/Plzq2qbfAPWsKh+6LGigTpc+YpSsmV3yaUgrkVl32ijeXEktaclciZEHgd+jmwudMArGsJ4umwMj3THNo9rJeW6A5EW3YFPvxxY/yMFPLi7gAlNrhWgTKF9uZxmo=
  
  # ENVELOPE_KMS_TEST_KEY_ID
  - secure: juPACWj6wy9Wot2oaw4G9YncwkJMOtDUKOdHzN8VJqjdmdRjJDTC5NC6lOMDD2pQE/iRJp/deVFR8pg5hmp8f1EhHGk+HF1jlEz/cs7Ag3h1RdpJW5MrKn4AL7H+8xEPSPIE0UKL6mFfdadCPcp9xiCt9DJIA3LvovYwrgLXDIqYBNWadwC/pdjZlLFPz7I9WT4PH7cltiTqSTZtSnxwSO/FUKQAfKreTq6aTkegz9V3Iiq5enKgRYlYAKT+wMAPZzLQUTwydwIWVkcoUGSUJE4cNjo3nyGQ1rZd5B1ZJPaxk9Y6M/tY562MW2aGzCQIT2oMYY9EATJgEj3m4Nj1b3SxUXDG5Fv61S1KckylsfjzBUd4tSsvoPcbQGc7fNK52GLLIWrvluQ4eguW9ZkXkLFclI+Y9rhHoUdD3pzjpYdsc3hAv3XIiNMjOLWoy7hbLekpgMH4SvT0arDEwbYSjwLW/EkNn0bCXlT3WwIYSq8O9qMMVv+xCZ3uUC4OIdlUoH1Qa3OsFq91k+vS9Xo7y17ID2Idoc2NPYeqxO70CmT8tJ7jjBXJjDKeBT/+LxU1TiHcKgPuK/A6Mu3+yz/kKgV358m4ML2lluHawK1QRtlFsTFa9H0sx329h2zFbDEF9rQRPdZYbvR/twhig4qOs6rvam2WjyLPEn+AFqUVvnk=
